variable "prefix" { }
variable "region" { }
variable "resource_group" { }
variable "subnet_id" { }
variable "ssh_username" { }
variable "ssh_key_path" { }
variable "mysqlAdmin" { }
variable "mysqlAdminPass" { }
variable "db_hostname" { }